add missing include for std::for_each
On NetBSD 8.0 x86_64, gcc complains:
 NUM3Parser.cpp: In member function 'virtual bool libetonyek::NUM3Parser::parseDocument()':
 NUM3Parser.cpp:46:3: error: 'for_each' is not a member of 'std'
   std::for_each(sheetListRefs.begin(), sheetListRefs.end(), std::bind(&NUM3Parser::parseSheet, this, std::placeholders::_1));

Change-Id: I723ba1bcbd10ed9215ceea8c5b224fdc5242be65
Reviewed-on: https://gerrit.libreoffice.org/c/libetonyek/+/94450
Tested-by: Thorsten Behrens <Thorsten.Behrens@CIB.de>
Reviewed-by: Thorsten Behrens <Thorsten.Behrens@CIB.de>