Fix -Werror=format-extra-args in IWAParser
In file included from IWAParser.h:32:0,
                 from IWAParser.cpp:10:
IWAParser.cpp: In member function ‘bool libetonyek::IWAParser::parsePath(const libetonyek::IWAMessage&, libetonyek::IWORKPathPtr_t&)’:
IWAParser.cpp:1004:122: error: too many arguments for format [-Werror=format-extra-args]
           ETONYEK_DEBUG_MSG(("IWAParser::parsePath: missing prior MoveTo subsequent LineTo\n", get(type) == 1 ? 'M' : 'L'));
                                                                                                                          ^
libetonyek_utils.h:51:53: note: in definition of macro ‘ETONYEK_DEBUG_MSG’
 #define ETONYEK_DEBUG_MSG(M) libetonyek::debugPrint M
                                                     ^
cc1plus: all warnings being treated as errors

Change-Id: Ic87e540fa4c2a80a0edac5fba88c1f2dce342233