workaround build problem with clang
error: default initialization of an object of const type 'const
test::(anonymous namespace)::TokenizerA' requires a user-provided
default constructor

Change-Id: I4f01d4de630ef5ebd21c5eaca476e6defda30d3e