Fix for regression caused by commit 7742191bb0971dc165170f86e
In standard behaviour, the libetonyek for Keynotes 5 documents should return:
   ERROR: Unsupported file format!
Unfortunately with cropping implementation it is randomly causing
crash.

This commit fixes that issue.

Change-Id: I9da2946d8b68ff8393fb3677702b971f4e62b2ad
Reviewed-on: https://gerrit.libreoffice.org/c/libetonyek/+/176974
Tested-by: Bartosz Kosiorek <gang65@poczta.onet.pl>
Reviewed-by: Bartosz Kosiorek <gang65@poczta.onet.pl>